### ISSUE TITLE
Can you make the version for windows please

### ISSUE THREAD

**Issue by liyingjie12345** [LouisOuellet/ftp-to-smb#1]

**Comment by LouisOuellet** [comment]
You can run this script on Windows 10 using WSL (Windows Subsystem for Linux).

You can install WSL by following this : https://docs.microsoft.com/en-us/windows/wsl/install-win10.

Alternatively, you can also use a virtual machine or a container to run linux.

This script does not require much. I run this on a small VM that run many other small apps like this one.

**Comment by liyingjie12345** [comment]
OK, thank you.

**Comment by LouisOuellet** [comment]
No problem
